name: CI/CD Pipeline

on:
  push:
    branches:
      - feat/noservicecontext

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Install flyctl
      #   run: |
      #     for i in {1..5}; do
      #       curl -sL https://install.fly.io/flyctl.sh | sh && break || sleep 15
      #     done
      #     echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_PATH

      - name: Check if only main.yml was changed
        id: check_files
        run: |
          git fetch
          COMMIT_HASHES=$(git rev-list -n 2 HEAD)
          PREVIOUS_COMMIT=$(echo "$COMMIT_HASHES" | tail -n 1)
          CURRENT_COMMIT=$(echo "$COMMIT_HASHES" | head -n 1)
          FILES_CHANGED=$(git diff --name-only $PREVIOUS_COMMIT $CURRENT_COMMIT)
          echo "Files changed between commits: $FILES_CHANGED"
          if [[ "$FILES_CHANGED" == *".github/workflows/main.yml"* ]] && [[ "$(echo "$FILES_CHANGED" | wc -l)" == "1" ]]; then
            echo "only_main_yml_changed=true" >> $GITHUB_ENV
          else
            echo "only_main_yml_changed=false" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        if: ${{ env.only_main_yml_changed == 'false' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ env.only_main_yml_changed == 'false' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lishoulong/gpt-reader-bot:v1.0.${{ github.run_number }}

      - name: Update fly.toml image version and push
        if: ${{ env.only_main_yml_changed == 'false' }}
        run: |
          sed -i "s|image = \"***/gpt-reader-bot:.*\"|image = \"***/gpt-reader-bot:v1.0.11\"|g" fly.toml
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add fly.toml
          git commit -m "Update fly.toml image version"
          git remote set-url origin https://x-access-token:${{ secrets.gpt_bot_auto_task }}@github.com/lishoulong/myGPTReader
          git push

      - name: Install flyctl and deploy
        run: |
          for i in {1..5}; do
            curl -sL https://install.fly.io/flyctl.sh | sh && break || sleep 15
          done
          export PATH=$HOME/.fly/bin:$PATH
          flyctl auth token ${{ secrets.FLY_API_TOKEN }}
          flyctl deploy
      # - name: Deploy to Fly.io
      #   run: |
      #     $HOME/.fly/bin/flyctl auth token ${{ secrets.FLY_API_TOKEN }}
      #     $HOME/.fly/bin/flyctl deploy
