name: CI/CD Pipeline

on:
  push:
    branches:
      - feat/noservicecontext # 指定在向主分支（main）推送代码时触发此工作流程

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lishoulong/gpt-reader-bot:v1.0.${{ github.run_number }}

      - name: Install Flyctl
        run: curl -L https://install.fly.dev | sh

      - name: Update fly.toml image version
        run: |
          sed -i "s|image = \"lishoulong/gpt-reader-bot:.*\"|image = \"lishoulong/gpt-reader-bot:v1.0.${{ github.run_number }}\"|g" fly.toml

      - name: Deploy to Fly.io
        run: |
          flyctl auth token ${{ secrets.FLY_API_TOKEN }}
          flyctl deploy
