name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feat/noservicecontext

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.GPT_BOT_AUTO_TASK }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install flyctl
        run: |
          curl -sL https://fly.io/install.sh | sh
          ls $HOME/.fly/bin
          echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_PATH

      - name: Check if only main.yml was changed
        id: check_files
        run: |
          git fetch
          COMMIT_HASHES=$(git rev-list -n 2 HEAD)
          PREVIOUS_COMMIT=$(echo "$COMMIT_HASHES" | tail -n 1)
          CURRENT_COMMIT=$(echo "$COMMIT_HASHES" | head -n 1)
          FILES_CHANGED=$(git diff --name-only $PREVIOUS_COMMIT $CURRENT_COMMIT)
          echo "Files changed between commits: $FILES_CHANGED"
          if [[ "$FILES_CHANGED" == *".github/workflows/main.yml"* ]] && [[ "$(echo "$FILES_CHANGED" | wc -l)" == "1" ]]; then
            echo "only_main_yml_changed=true" >> $GITHUB_ENV
          else
            echo "only_main_yml_changed=false" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        if: ${{ env.only_main_yml_changed == 'false' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get latest Docker image tag and increment version
        if: ${{ env.only_main_yml_changed == 'false' }}
        id: get_latest_tag
        run: |
          LATEST_TAG=$(docker run --rm -e GH_TOKEN=${{ secrets.GPT_BOT_AUTO_TASK }} ghcr.io/cli/cli gh repo view lishoulong/gpt-reader-bot --json tags -q '.tags[0].name')
          echo "Latest tag: $LATEST_TAG"
          NEW_VERSION=$(echo $LATEST_TAG | awk -F. '{$NF+=1; OFS="."; print $0}')
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        if: ${{ env.only_main_yml_changed == 'false' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lishoulong/gpt-reader-bot:${{ env.NEW_VERSION }}

      - name: Update fly.toml image version
        if: ${{ env.only_main_yml_changed == 'false' }}
        run: |
          sed -i "s|image = \"lishoulong/gpt-reader-bot:.*\"|image = \"lishoulong/gpt-reader-bot:${{ env.NEW_VERSION }}\"|g" fly.toml
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add fly.toml
          git commit -m "Update fly.toml image version"

      - name: Push changes using ad-m/github-push-action
        if: ${{ env.only_main_yml_changed == 'false' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GPT_BOT_AUTO_TASK }}
          branch: feat/noservicecontext

  deploy:
    needs: build_and_deploy
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
