name: CI/CD Pipeline

on:
  push:
    branches:
      - feat/noservicecontext

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install flyctl
        run: |
          for i in {1..5}; do
            curl -sL https://install.fly.io/flyctl.sh | sh && break || sleep 15
          done
          echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_ENV

      - name: Check if only main.yml was changed
        id: check_files
        run: |
          git fetch
          FILES_CHANGED=$(git diff --name-only HEAD..FETCH_HEAD)
          if [ "$FILES_CHANGED" == ".github/workflows/main.yml" ]; then
            echo "::set-output name=only_main_yml_changed::true"
          else
            echo "::set-output name=only_main_yml_changed::false"
          fi

      - name: Print only_main_yml_changed value
        run: |
          echo "only_main_yml_changed: ${{ steps.check_files.outputs.only_main_yml_changed }}"

      - name: Login to Docker Hub
        if: ${{ steps.check_files.outputs.only_main_yml_changed == 'false' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ steps.check_files.outputs.only_main_yml_changed == 'false' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lishoulong/gpt-reader-bot:v1.0.${{ github.run_number }}

      - name: Update fly.toml image version and push
        if: ${{ steps.check_files.outputs.only_main_yml_changed == 'false' }}
        run: |
          sed -i "s|image = \"***/gpt-reader-bot:.*\"|image = \"***/gpt-reader-bot:v1.0.11\"|g" fly.toml
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add fly.toml
          git commit -m "Update fly.toml image version"
          git remote set-url origin https://x-access-token:${{ secrets.gpt_bot_auto_task }}@github.com/lishoulong/myGPTReader
          git push

      - name: Deploy to Fly.io
        run: |
          flyctl auth token ${{ secrets.FLY_API_TOKEN }}
          flyctl deploy
